clone test

diff --git a/src/commands/update-submodule.yml b/src/commands/update-submodule.yml
--- a/src/commands/update-submodule.yml
+++ b/src/commands/update-submodule.yml
@@ -22,26 +22,21 @@ steps:
       fingerprints:
         - << parameters.submodule-fingerprint >>
   - run:
-      name: confirm
+      name: update submodule
       command: |
-        echo << parameters.submodule-fingerprint >>
-        ls ~/.ssh/
-        _key=$(echo << parameters.submodule-fingerprint >> | sed -e 's/://g')
-        export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_${_key}"
-        echo $GIT_SSH_COMMAND
+        if [ -n << parameters.module-name >> ]; then
+          module_name=$(eval echo << parameters.module-name >>)
+          commit_message=$(echo << parameters.commit-message >>)
 
-  # - run:
-  #     name: update submodule
-  #     command: |
-  #       if [ -n << parameters.module-name >> ]; then
-  #         module_name=$(eval echo << parameters.module-name >>)
-  #         commit_message=$(echo << parameters.commit-message >>)
-  #         git config --global user.email "submodule.updater@rhems-japan.co.jp"
-  #         git config --global user.name "submodule-updater"
-  #         git submodule update --init --remote --recursive << parameters.module-name >>
-  #         git status
-  #         git commit -a -m "${commit_message}" || true
-  #         git push -u origin ${CIRCLE_BRANCH}
-  #       else
-  #         echo "target not found."
-  #       fi
+          _key=$(echo << parameters.submodule-fingerprint >> | sed -e 's/://g')
+          export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_${_key}"
+
+          git config --global user.email "submodule.updater@rhems-japan.co.jp"
+          git config --global user.name "submodule-updater"
+          git submodule update --init --remote --recursive << parameters.module-name >>
+          git status
+          git commit -a -m "${commit_message}" || true
+          git push -u origin ${CIRCLE_BRANCH}
+        else
+          echo "target not found."
+        fi
