te

diff --git a/src/commands/update-submodule.yml b/src/commands/update-submodule.yml
--- a/src/commands/update-submodule.yml
+++ b/src/commands/update-submodule.yml
@@ -19,18 +19,25 @@ steps:
       name: confirm
       command: echo << parameters.module-name >>
   - run:
-      name: update submodule
+      name: confirm
       command: |
-        if [ -n << parameters.module-name >> ]; then
-          module_name=$(eval echo << parameters.module-name >>)
-          commit_message=$(echo << parameters.commit-message >>)
-          git config --global user.email "submodule.updater@rhems-japan.co.jp"
-          git config --global user.name "submodule-updater"
-          git submodule update --init --remote --recursive << parameters.module-name >>
-          git status
-          git commit -a -m "${commit_message}" || true
-          git push -u origin ${CIRCLE_BRANCH}
-        else
-          echo "target not found."
-        fi
+        echo << parameters.submodule-fingerprint >>
+        cat ~/.ssh/
+        echo << parameters.submodule-fingerprint >> | sed -e 's/://g'
       # export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_12d1254452bda7f998b2799e7cd2a679"
+
+  # - run:
+  #     name: update submodule
+  #     command: |
+  #       if [ -n << parameters.module-name >> ]; then
+  #         module_name=$(eval echo << parameters.module-name >>)
+  #         commit_message=$(echo << parameters.commit-message >>)
+  #         git config --global user.email "submodule.updater@rhems-japan.co.jp"
+  #         git config --global user.name "submodule-updater"
+  #         git submodule update --init --remote --recursive << parameters.module-name >>
+  #         git status
+  #         git commit -a -m "${commit_message}" || true
+  #         git push -u origin ${CIRCLE_BRANCH}
+  #       else
+  #         echo "target not found."
+  #       fi
